### ISSUE TITLE
速度有些慢呀，要是能快点就好了

### ISSUE THREAD

**Issue by mathCrazyy** [mtchetch/wiztree-csv-generator#1]
嗯嗯呢~

**Comment by mtchetch** [comment]
I am only able to respond in english. The speed is indeed on the slow side. It is possible to optimize the code to make it faster but so far I have not had time to do so. Please feel free to contribute if you are able to optimize the code.

**Comment by mtchetch** [comment]
Re wrote the script to be more efficient.

**Comment by mathCrazyy** [comment]
thank you very much~new code also flush the result make me feel ease
